### ISSUE TITLE
windows能用吗 

### ISSUE THREAD

**Issue by fangkaiyu** [KaiJin1995/tesseract_cardRecognition#1]
编译能通过，但是按照你给的例子在demo.pu路径下命令行不能 通过

**Comment by KaiJin1995** [comment]
我用ubuntu16.04运行， windows应该也可以，可以把报错截图发给我看看

**Comment by fangkaiyu** [comment]
![default](https://user-images.githubusercontent.com/41827241/44627507-b77acb80-a961-11e8-9ef9-c8601fe4abfd.PNG)
运行报错或者没有result

**Comment by KaiJin1995** [comment]
你缺少参数了  运行的时候需要把图片路径放上去 ， 我找的是建造业工人注册证的图像   
![image](https://user-images.githubusercontent.com/14345526/44629106-f9653b00-a97c-11e8-93fc-26b10b706a3c.png)
运行的时候 需要 python  card_demo  image_path 。
图片可以百度上找“建造业工人注册证”
